# Generated by Django 2.0.1 on 2018-01-31 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20180129_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='guardian',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='school.Guardian'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='school.StudentGroup'),
        ),
    ]
