# Generated by Django 2.0.1 on 2018-02-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20180201_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assesment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assesment_type', models.CharField(max_length=50)),
                ('assesment_amount', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='guardian',
            name='full_name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
