# Generated by Django 2.0.1 on 2018-02-02 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20180202_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAssesment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assesment_date', models.DateTimeField(auto_now_add=True)),
                ('result', models.DecimalField(decimal_places=2, max_digits=5)),
                ('assesment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Assesment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='assesments',
            field=models.ManyToManyField(through='school.StudentAssesment', to='school.Assesment'),
        ),
    ]
